### ISSUE TITLE
Ramp up README

### ISSUE THREAD

**Issue by akshatshah21** [saharshleo/chattingApp#1]
Here are a few points I'd like to add/modify in the README:

- The screenshots should be lower in the README
- Links to the documentation pages of the libraries
- Contributors section

**Comment by saharshleo** [comment]
@akshatshah21 point 1 and 3 are done, you can do the second?

**Comment by akshatshah21** [comment]
Yes, okay @saharshleo

**Comment by akshatshah21** [comment]
This work has been completed in PR #3
